### ISSUE TITLE
Связать обогащение и обнаружение угроз на лету

### ISSUE THREAD

**Issue by neexee** [neexee/mca-workshop#10]
Нужно написать прослойку между моделью, обогащением и читалкой логов.

![image](https://user-images.githubusercontent.com/536030/89852033-29349a00-dbb8-11ea-9b38-f9dd694c82b6.png)

**Comment by neexee** [comment]
@slendas1
Обогащение - это три функции
```
def get_ip_score(ip: str) -> int:
    pass

def get_domain_score(domain: str) -> int:
    pass

def get_file_hash_score(hash: str) -> int:
    pass
```
Реализуйте этот интерфейс, пожалуйста.

**Comment by neexee** [comment]
@jerrytwsix 
Как писал @sciton в https://github.com/neexee/mca-workshop/issues/6#issuecomment-671311285

Читалка логов должна генерировать списки таких объектов и передавать их в прослойку (шаг 1): 
```
@dataclass
class ProcessCreation:
    Time: datetime.datetime # Время запуска процесса
    Hashes: List[str] # Хеши запущенного файла
    GUID: str # Id процесса
    Name: str # Имя запущенного файла
    User: str # Имя пользователя
    Host: str # Имя хоста

@dataclass
class NetworkConnection:
    Time: datetime.datetime # Время установления соединения
    Domain: str # Пустая строка, если подключение по IP
    IP: str
    Protocol: str # TCP/UDP и так далее 
```
Пожалуйста, переделай возвращаемые значения функции scan.

**Comment by neexee** [comment]
@sciton @t4rqus
В модель будут передаваться примерно такие структуры (на шаге 4):
```
@dataclass
class ProcessCreationEnriched:
    Time: datetime.datetime # Время запуска процесса
    Hashes: List[str] # Хеши запущенного файла
    Score: int # Скор файла
    GUID: str # Id процесса
    Name: str # Имя запущенного файла
    User: str # Имя пользователя
    Host: str # Имя хоста

@dataclass
class NetworkConnectionEnriched:
    Time: datetime.datetime # Время установления соединения
    Domain: str # Пустая строка, если подключение по IP
    DomainScore: int
    IP: str
    IPScore: int
    Protocol: str # TCP/UDP и так далее 
```

То есть интерфейс у модели должен быть примерно такой:
```
def calculate_risk(processes: List[ProcessCreationEnriched], connections: List[NetworkConnectionEnriched]) -> int:
    pass
```
Норм?

**Comment by sciton** [comment]
В NetworkConnectionEnriched будет здорово, если оставить только один Score, например, максимальный из IPScore и DomainScore

(up)
Может так?
class NetworkConnectionEnriched:
    Time: datetime.datetime # Время установления соединения
    Domain: str # Пустая строка, если подключение по IP
    IP: str
    Score: int
    Protocol: str # TCP/UDP и так далее 
    Name: имя юзера, который запустил соединение
    Host: имя компа


А еще и туда и туда было бы здорово записать EventID

**Comment by neexee** [comment]
Реализовано, закрываю.
