### ISSUE TITLE
Обнаружение угроз на лету

### ISSUE THREAD

**Issue by neexee** [neexee/mca-workshop#2]
Jupyter-плейбук APT29 заточен на статический файл с логом. В реальности так не бывает, логи приезжают в анализатор по одной строке. 

# Задание
Нужно реализовать модуль, который сообщает об атаке при первом же появлении её признаков в логе. Начать можно с JSON-логов Mordor project, в идеале научиться разбирать логи sysmon и читать их в реалтайме.

В итоге для определения угроз нужно будет использовать #3.

**Comment by jerrytwsix** [comment]
### **Цель:**
Реализовать модуль, который обрабатывает логи sysmon на появление в них признаков атаки и выдает тактики/техники, которые потенциально могли использоваться.

**Вход:**
Логи Sysmon и/или JSON-логи Mordor project.
**Выход:** 
Тактика->Техника по ATT&CK; логи подозрительных записей. 

### Features of this module:
Analyze the logs from Sysmon or JSON’s from Mordor project.
Search the sign of attack in logs.
Realize a tactic or a technique of attack.
Structure the information about attacks in one result log. 

### Задачи:
Написать программу, которая:

- Детектит в логах Sysmon подозрительные записи.

- Определяет по ним тактику/технику ATT&CK.

- Выводит в итоговый лог эти записи с техниками.

**Comment by neexee** [comment]
Как работает программа, что принимает на вход? Можно ей сказать с какой даты читать логи?
Как понять, что запись в логе подозрительная? Как будут реализованы правила, которые по записи определяют, что запись подозрительная?

**Comment by jerrytwsix** [comment]
Было бы очень удобно принимать JSON, как в логах mordor project, там все данные в словарях python, но sysmon по умолчанию естественно не может выдавать такое, там xml,csv,evtx форматы на выходе, но я думаю наверняка уже есть готовое решение, чтобы их в json переводить.
Можно будет задать дату, с которой нужно читать логи, в sysmon логах есть поле UtcTime, где дата в формате yyyy-mm-dd hh:mm:ss.mls, задать условие WHERE user_date >= UtcTime
С правилами, по которым распознается, подозрительная ли запись пока затык, не совсем понимаю как нам без каких-либо вспомогательных данных понимать, например, подозрительный ли процесс запустил пользователь, или нет. Возможно стоит включить какие-то опции, чтобы распознать ту или иную тактику. Например включить возможность ввода имен потенциально опасных процессов, которые могут маскироваться.

**Comment by neexee** [comment]
В логе у записей есть полезные кусочки информации. Например, хеш файла, который был запущен. Или IP, к которому коннектимся. Эти кусочки можно отправлять в модель (#3), она разберётся, что с ними делать. Только их нужно обогатить через #6 и отправить в модель #3. Договоритесь только, какими структурами данных вы будете общаться :)

**Comment by jerrytwsix** [comment]
Тогда мы собираем хеши файлов и IP-шники подключений и из них делаем логи, которые отправляются в 6?

**Comment by neexee** [comment]
6 это просто три функции, они принимают не логи, а IP, домены или файлы.
```
def enrich_ip(address: str) -> IpInfo:
    pass


def enrich_domain(domain: str) -> DomainInfo:
    pass


def enrich_file(file_hash: str) -> FileInfo:
    pass
```
Но в целом ты прав, здесь нужно выгребать IP, домены и хеши из sysmon, отправлять их в 6, а потом что получилось отправлять в 3.

**Comment by neexee** [comment]
Реализовано, закрываю.
