### ISSUE TITLE
Модель рисков

### ISSUE THREAD

**Issue by neexee** [neexee/mca-workshop#3]
Продумать и реализовать модель рисков. 
По факту это сводится к реализации формулы расчёта риска при обнаружении тактики. Но формула непростая, нужно учесть много вещей.
Например:
* Тип пользователя (разработчик, админ, глава компании))
* Важность системы (боевая база данных, почтовый сервер, рабочая машина)
* ... и так далее

Придумать, что можно сделать с рисками:
* Если риск из формулы выше большой (задействована всего одна тактика, но она критичная и требует внимания человека)
* Если обнаружено сразу несколько тактик ATT&CK (кто-то продвигается по kill chain)
* Если обнаружено много уникальных техник ATT&CK (кто-то занимается перебором)
* Если число обнаруженных техник резко подскакивает
* Если разные источники одновременно сообщают, что риск вырос

Данные будут доставлять #6 и #5.
См. также [статью](http://intaver.com/risk-scores/)

**Comment by sciton** [comment]
+1

**Comment by t4rqus** [comment]
+1

**Comment by sciton** [comment]
Описание
------------
В корпоративной сети могут существовать десятки или даже сотни угроз. Угрозы имеют разный приоритет и реакция администраторов сети должна быть направлена на наиболее серьезные угрозы. Поэтому необходимо оценивать угрозы, возникающие в процессе работы компании.
Процесс моделирования угроз носит итерационный характер. На каждом шаге выполняются следующие действия:
1. Определение объектов для защиты (базы данных, железо, итд)
2. Обзор системы. Необходимо выявить основные характеристики системы и ее пользователей.
3. Рассмотрение архитектуры системы. Требуется подробно описать механизм работы системы
4. Определение угроз. Что может сделать злоумышленник по отношению к объектам для защиты. При поиске необходимо опираться на пункты 2 и 3.
5. Определение уязвимостей. Определить возможные механизмы осуществления угроз на основе механики работы системы.

![](https://user-images.githubusercontent.com/18235530/88771879-8b3cda80-d188-11ea-9c93-2122e6f366a9.png)

Каждая угроза имеет вероятность осуществления и некоторый урон для предприятия. Урон от осуществления угрозы оценивается исходя из того, как и для чего работает данная система. Степень урона можно оценить по 10-бальной шкале, где 0 - никакого урона, 10 - критический урон. Риск равен произведению вероятности осуществления угрозы на урон.

Таким образом, у системы есть набор угроз. Эти угрозы могут быть связаны между собой, т.е. выполнение одной угрозы увеличивает вероятность выполнения другой угрозы. 

Каждая угроза имеет некоторый набор индикаторов, по выполнению которых мы можем говорить о вероятности осуществления угрозы. Индикаторы связаны с известными уязвимостями системы. 

Модель должна работать следующим образом. При запуске программы мы передаем ей файл, в котором содержатся угрозы (урон, таблица: список индикаторов->вероятность->флаг, (связанные угрозы)). Далее каждое подозрительное событие в системе отправляется в программу. Программа проверяет, есть ли это событие в списке индикаторов. Если есть, то по выполненным индикаторам оценивает вероятность, рассчитывает для каждой угрозы риски, суммирует и возвращает результат. Иначе возвращает 0. Ставит флаг на найденном индикаторе.

Входные данные: (при запуске) JSON - файл со списком угроз, (при подозрительном событии) - индикатор.
Выходные данные: число (оценка риска для подозрительного события) 

Индикаторы: 
(_заполнить позже_)

TODO:
-------
![](https://user-images.githubusercontent.com/18235530/88846693-a6dacc00-d1ee-11ea-8dae-9bf5ac952231.png)

1. Рассмотреть конкретную систему, определить угрозы и уязвимости, определить возможные индикаторы для каждой уязвимости.
2. Сделать входной файл для модели, в котором прописаны угрозы (урон и таблица: список индикаторов->вероятность->флаг)
3. Написать скрипт, который считывает файл с угрозами, а затем обрабатывает каждое входящее событие.

**Ресурсы**:
1. [Threat Modeling](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff648644(v=pandp.10)
)
2. [How To: Create a Threat Model for a Web Application at Design Time](https://docs.microsoft.com/en-us/previous-versions/msp-n-p/ff647894(v=pandp.10)?redirectedfrom=MSDN)

Возможные полезные ресурсы:
1. [Attack Modeling forInformation Security and Survivability](https://resources.sei.cmu.edu/asset_files/TechnicalNote/2001_004_001_13793.pdf)
2. [MultiDimensional Analysis of Major Risks in ComplexProjects](https://www.researchgate.net/publication/247479510_A_MultiDimensional_Analysis_of_Major_Risks_in_Complex_Projects)
3. [Operationally Critical Threat, Asset, and Vulnerability Evaluation SM (OCTAVESM) Framework, Version 1.0](https://resources.sei.cmu.edu/asset_files/TechnicalReport/1999_005_001_16769.pdf)

**Comment by sciton** [comment]
Пример
---------
Пк, win10, подключен через роутер в инет, 
злоум хочет прониктуть на комп и постановить программу для рассылки спама

Сценарий атаки (взлом почты)
1. злоум передает какой-то малварь на компьютер 
Индикаторы: 
а. найден хэш какого-то марваря
б. запуск подозрительного процесса
в. выполнение подозрительных команд powershell/cmd

2. программа делает подключение через открытый порт
Индикаторы:
а. открыт нестандартный порт
б. выполнение системного вызова winsock2
3. программа пересылает куки

**Comment by sciton** [comment]
DFD threat models
-------------------
Ссылки
1. https://www.microsoft.com/en-us/securityengineering/sdl/threatmodeling
2. https://www.geeksforgeeks.org/microsoft-threat-modelling-tool-2016-set-1/
3. https://www.geeksforgeeks.org/microsoft-threat-modelling-tool-2016-set-2/

**Comment by t4rqus** [comment]
### **Несколько поясняющих картинок**
![image](https://user-images.githubusercontent.com/68426160/88874508-6eb4a700-d249-11ea-8790-f962c73b5bbb.png)
**Защита информации** - обеспечение целостности, конфиденциальности, доступности информационных ресурсов. Кроме этого, дополнительными свойствами информации в состоянии защищенности являются неотказуемость, подлинность, подотчетность.

**Угроза** безопасности информации - потенциальная причина возникновения нежелательного инцидента информационной безопасности, который может нанести ущерб активам и нарушить состояние защищенности информации; инциденту может предшествовать несанкционированное изменение состояния актива, называющееся событием информационной безопасности.

**Источником** угрозы могут являться внешние или внутренние (по отношению к рассматриваемому объекту защиты) нарушители, третьи лица, силы природы. 

**Моделирование угроз** — это идентификация всех угроз, которые могут нанести ущерб активам, и векторов атак, которые могут быть использованы источниками угроз для нанесения ущерба.

**Уязвимость** — это недостаток средств защиты информационной системы, который может быть использован нарушителем (как внешним, так и внутренним) для реализации угроз информационной безопасности. Уязвимости информационной системы могут быть порождены как ошибками при создании, внедрении или эксплуатации системы, так и слабостью наложенных защитных средств и примененных мер.

**Риск** ИБ - потенциальная возможность использования уязвимостей активов конкретной угрозой для причинения ущерба организации. Как и в классическом риск-менеджменте, есть следующие способы обработки киберриска: игнорировать, принять, избежать, передать, минимизировать. Выбор именно последнего, наиболее оптимального во многих случаях способа обработки риска предшествует разработке и внедрению систем и средств информационной безопасности.

На _рис. 2.1_ представлена определяемая стандартом взаимосвязь высокоуровневых понятий в области ИБ. Безопасность связана с защитой активов ИС от угроз. За сохранность рассматриваемых активов отвечают их владельцы, для которых эти активы имеют ценность. Существующие или предполагаемые нарушители также могут придавать значение этим активам и стремиться использовать их вопреки интересам их владельца. Владельцы будут воспринимать подобные угрозы как потенциал воздействия на активы, приводящего к понижению их ценности для владельца.
Владельцы активов будут анализировать возможные угрозы, чтобы решить, какие из них действительно присущи их среде. В результате анализа определяются риски. Анализ может помочь при выборе контрмер для противостояния угрозам и уменьшения рисков до приемлемого уровня.
Контрмеры предпринимают для уменьшения уязвимостей и выполнения политики безопасности владельцев активов (прямо или косвенно распределяя между этими составляющими). Но и после введения этих контрмер могут сохраняться остаточные уязвимости. Такие уязвимости могут использоваться нарушителями, представляя уровень остаточного риска для активов. Владельцы будут стремиться минимизировать этот риск, задавая дополнительные ограничения.

![image](https://user-images.githubusercontent.com/68426160/88877722-66ac3580-d250-11ea-82f8-68d067feab97.png)
_ВеличинаРиска_ = _ВероятностьСобытия_ * _РазмерУщерба_, где
_ВероятностьСобытия_ = _ВероятностьУгрозы_ * _ВеличинаУязвимости_



**Отношения между бизнесом, IT и рисками**
![image](https://user-images.githubusercontent.com/68426160/88879909-9c9fe880-d255-11ea-8e07-6ac03ec20a79.png)

**Ссылки**

1. [Основные понятия и парадигма оценки рисков](https://habr.com/ru/post/467943/), а также остальные статьи Рахметова
2. [MITRE Cyber Threat Modeling](https://www.mitre.org/sites/default/files/publications/pr_18-1174-ngci-cyber-threat-modeling.pdf)

**Comment by sciton** [comment]
**Презентации микрософта по моделированию угроз**
https://www.microsoft.com/en-us/download/details.aspx?id=16420

**Comment by neexee** [comment]
Реализовано, задачу закрываю. На доработки можно завести отдельную задачу.
