### ISSUE TITLE
Эмуляция атакующих

### ISSUE THREAD

**Issue by neexee** [neexee/mca-workshop#4]
Научиться эмулировать действия атакующих с помощью [Caldera](https://github.com/mitre/caldera) ([видео с демонстрацией](https://www.youtube.com/watch?v=xjDrWStR68E)).
Сэмулировать действия APT29 с помощью неё. Возможно, понадобится написать плагин, реализующий технику ATT&CK.

**Comment by EmelyanovAndreyNSK** [comment]
Задачи: 
1. Научиться эмулировать действия атакующих с помощью Caldera.
2. Сэмулировать действия APT29 с помощью неё.
3. Написать плагин, реализующий технику ATT&CK.
4. Получить логи, содержащие информацию о ходе атаки.

**Comment by neexee** [comment]
Как будете делать пункты 1 и 2?

**Comment by EmelyanovAndreyNSK** [comment]
Планируем выполнить эти пункты последовательно

**Comment by neexee** [comment]
Отличный ответ, но я хотел немного другого :) Знаешь, есть такой фреймворк, называется [SMART](https://ru.wikipedia.org/wiki/SMART)?

То есть в нём для шага 1 нужно ответить на вопросы:
S. Как вы поймёте, что научились эмулировать атакующих?
M. На скольки атакующих и атакуемых? Всё виртуальное или что-то реальное? Сколько техник/тактик попробуете?
A. Как вы будете настраивать Caldera?
R. С шагом 1 вопросов нет.
T. До конца этой недели какие шаги будут сделаны?

По-хорошему прогнать бы все шаги через SMART, ответы на вопросы записать тут.

**Comment by EmelyanovAndreyNSK** [comment]
1. Установить Caldera на ПК, запустить с помощью Docker, для эмуляции действий атакующих.
2. Воспроизвести примеры техник, приведенные в Caldera  Plugins -> Training, для лучшего освоения Caldera.

**Comment by neexee** [comment]
Атаку провели, логи собрали. Задачу можно считать закрытой.
