### ISSUE TITLE
Обогащение информации о файлах, доменах и IP

### ISSUE THREAD

**Issue by neexee** [neexee/mca-workshop#6]
В логах часто проскакивают хеши файлов, IP и домены. Поэтому для их анализа нужно автоматизировать:
* Получение информации о файлах (по хешам) из [VirusTotal](https://developers.virustotal.com/v3.0/reference). Важнее всего информация о том, что файл малварь и уровень его опасности.
* Получение информации о доменах из DNS. Если у домен зарегистрирован недавно (день назад) или он похож на [DGA](https://en.wikipedia.org/wiki/Domain_generation_algorithm)-генерированный, повышать уровень его опасности.
* Получение информации о доменах и IP из Whois.

**Comment by slendas1** [comment]
Наш проект будет состоять из двух частей.
Первая: по файлу определяет является ли он вредоносной программой с помощью VirusTotal.
Входные данные:
     файл или хеш файла
Выходные данные:
     "undetected" если все антивирусы не обнаружили вирус
      "detected" иначе
Вторая: по ip или доменному имени определяет является ли домен подозрительным, может ли он использоваться злоумышленниками. На самом деле пока что готова часть без суждения о том является ли домен подозрительным. 
А именно, написана функция на python.
Входные данный: ipv4 или ipv6 или доменное имя.
Выходные данные: в формате json c полями о времени создания домена, его правообладателя, стране и другое.

Про интеграцию: 
Мы видим наш проект так, что он будет включен в программу чтения логов как две библиотеки на языке питон.  Вопрос в том как будет написано чтение лога и на чем?

**Comment by neexee** [comment]
Спасибо, годное описание.

Чтение логов тоже на Python будет. Но вы сильно не переживайте про вызывающую сторону, просто сделайте удобную библиотеку. Может, она потом вообще в другом проекте каком-нибудь пригодится :)

**Comment by neexee** [comment]
Нужны три функции
```
def get_ip_score(ip: str) -> int:
    pass

def get_domain_score(domain: str) -> int:
    pass

def get_file_hash_score(hash: str) -> int:
    pass
```

**Comment by sciton** [comment]
Для создания процесса (event 1)
process:
name - имя процесса в командной строке (например, python.exe)
user - имя пользователя, который запустил процесс
host - имя компьютера в локальной сети
hash_score - степень опасности

Для сетевого подключения (event 3)
netcon:
domain - имя адреса
ip4 - собственно, айпи
type - тип соединения tcp\udp
